version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: alexgon/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_values:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: alexgon/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - backend


volumes:
  db_data:
  static_value:
  media_value:
  static_value_backend:
  media_value_backend:
