# Generated by Django 2.2.16 on 2023-05-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0002_auto_20230517_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredientAmount', to='ingredients.Ingredient', verbose_name='ингридиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(verbose_name='Текстовое описание'),
        ),
    ]
