# Generated by Django 2.2.16 on 2023-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230518_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tag_recipes', through='recipes.TagRecipe', to='recipes.Tag', verbose_name='тег'),
        ),
    ]
