# Generated by Django 2.2.16 on 2023-05-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230518_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredientamount',
            options={'verbose_name': 'Количество ингридиента в рецепте', 'verbose_name_plural': 'Количество ингридиентов в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Теги рецептов'},
        ),
    ]
